// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://komccfeyvjmuyvbtnhno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtvbWNjZmV5dmptdXl2YnRuaG5vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQyMTE5OTQsImV4cCI6MjA2OTc4Nzk5NH0.Rk2dTbojxPLDwSpN_4LZZ1XHeas7Fujwga2szxuHld8";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});